#General Settings
php_version: "8.2"
db_name: "gadd_agent"
db_host: "127.0.0.1"
db_username: "gadd_user"
db_password: "G@ddP@ss"
app_url: "http://172.30.69.190/backend"

# BitBucket
bitbucket_user: "ayaseen_wakeb"
bitbucket_token: "ATBB7Dqn7U3hmpgsUTXkUku7NjL3C4398339"

# Frontend public variables
NEXT_PUBLIC_API_URL: "http://localhost:3000"
NEXT_PUBLIC_SOCKET_URL: "ws://localhost:6001"
NEXT_PUBLIC_SOCKET_APP_KEY: "localdevkey"


#Mongo db variables
mongo_db_name: "gadd_socket"
mongo_username: "gadd_mongo"
mongo_password: "GaddMongoPass123!"

